name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t levonet/nginx:${DOCKER_TAG} .
    - name: Run test
      run: |
        cd test
        make
