name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_TAG: ${{ github.sha }}
      run: docker build -t levonet/nginx:${DOCKER_TAG} .
